### ISSUE TITLE
The phpmyadmin container won't go up!

### ISSUE THREAD

**Issue by islamath** [fnerdman/lamp-helm-repository#2]
the phpmyadmin container isn't firing up because the cmd expects an /etc/nginx.conf to be there!
`command: [sh, -c, sed -i 's/listen\ 80/listen {{ 
.Values.phpmyadmin.port
 }}/g' /etc/nginx.conf && /run.sh supervisord -n]
`
the official phpmyadmin image doesn't include an nginx.conf

**Comment by fnerdman** [comment]
Thanks Mohamed!
The issue here is that the phpmyadmin containers application by default listens on port 80, which is already used by the main httpd service. phpmyadmin should idealy be seperated from the main pod into its own deployment.
Would you want to supply a PR that fixes this issue?

**Comment by roadfox** [comment]
just opened a PR to fix this issue

**Comment by fnerdman** [comment]
fixed in #3
